url: "http://kylearector.com"
title: Kyle Rector
description: "I am a developer and mechanical designer living in Indianapolis. My passions include 3D printing, CAD programming, connected devices, and natural user interface development. I am a nut for new technology and IoT projects."
language: en-us

author: Kyle Rector 
email: kylearector@outlook.com	

permalink: /:year/:month/:title

gems:
  - jekyll-sitemap

exclude:
  - CNAME
  - Gemfile
  - LICENSE.txt
  - README.md

google:
  analytics:
    profile: 'UA-59815038-1'

disqus:
  shortname: kylearector

twitter:
  username: kylearector

linkedin:
  username: kylearector

encoding: UTF-8
