url: "http://kylearector.com"
title: Kyle Rector
description: "I am a mechanical designer and developer, working at Gulfstream in Savannah. My fiance and I are proud Purdue University alumni, and together we are raising a wonderful mutt, Faye, and a Roomba named Chappie. I am extremely driven to improve CAD UX by any means possible, and am a nut for anything in the IoT."
language: en-us

author: Kyle Rector 
email: kylearector@outlook.com	

permalink: /:year/:month/:title

gems:
  - jekyll-sitemap

exclude:
  - CNAME
  - Gemfile
  - LICENSE.txt
  - README.md

google:
  analytics:
    profile: 'UA-59815038-1'

disqus:
  shortname: kylearector

twitter:
  username: kylearector

linkedin:
  username: kylearector
